#!/bin/sh

uci -q batch <<-EOF >/dev/null
    set openvpn.bitcord_demo_vpnjantit=openvpn
    set openvpn.bitcord_demo_vpnjantit.config='/etc/openvpn/bitcord_demo_vpnjantit.ovpn'
    set openvpn.bitcord_demo_vpnjantit.enabled='1'
    set openvpn.bitcord_demo_vpnjantit.auth_user_pass='/etc/openvpn/bitcord_demo_vpnjantit.auth'
    commit openvpn
    set network.openvpn=interface
    set network.openvpn.proto='none'
    set network.openvpn.delegate='0'
    set network.openvpn.ifname='tun0'
    commit network
EOF

exit 0