#!/bin/sh

uci -q batch <<-EOF >/dev/null
    add firewall zone
    set firewall.@zone[-1].name='vpn'
    set firewall.@zone[-1].input='ACCEPT'
    set firewall.@zone[-1].output='ACCEPT'
    set firewall.@zone[-1].forward='ACCEPT'
    set firewall.@zone[-1].masq='1'
    set firewall.@zone[-1].mtu_fix='1'
    set firewall.@zone[-1].network='openvpn'
    add firewall forwarding
    set firewall.@forwarding[-1].src='lan'
    set firewall.@forwarding[-1].dest='vpn'
    add firewall forwarding
    set firewall.@forwarding[-1].src='3g'
    set firewall.@forwarding[-].dest='lan'
    add firewall forwarding
    set firewall.@forwarding[-1].src='3g'
    set firewall.@forwarding[-1].dest='vpn'
    add firewall forwarding
    set firewall.@forwarding[-1].src='vpn'
    set firewall.@forwarding[-1].dest='3g'
    add firewall forwarding
    set firewall.@forwarding[-1].src='vpn'
    set firewall.@forwarding[-1].dest='lan'
    commit firewall
EOF

exit 0


